-- require('core.plugin_config.gruvbox')
require("core.plugin_config.nvim-tree")
require("core.plugin_config.lualine")
require("core.plugin_config.telescope")
-- require('core.plugin_config.wilder')
require("core.plugin_config.lsp_config")
require("core.plugin_config.completion")
require("core.plugin_config.treesitter")
-- require('core.plugin_config.night-owl')
require("core.plugin_config.goto-preview")
require("core.plugin_config.toggleterm")
require("core.plugin_config.navigator")
require("core.plugin_config.nvim-colorizer")
-- require('core.plugin_config.tokyonight')
require("core.plugin_config.diffview")
require("core.plugin_config.move")
require("core.plugin_config.lspsaga")
require("core.plugin_config.colorscheme")
require("core.plugin_config.indent-blankline")
require("core.plugin_config.nvim-ts-rainbow2")
require("core.plugin_config.treesitter-indent-object")
require("core.plugin_config.nvim-treesitter-context")
-- require('core.plugin_config.nvim-treesitter-textobjects')
require("core.plugin_config.comment")
require("core.plugin_config.nvim-next")
require("core.plugin_config.auto-session")
require("core.plugin_config.trouble")
